'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18052
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PartyIdea.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property aguno() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("aguno", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property party_splash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("party_splash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property quuno() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("quuno", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;root&gt;
        '''  &lt;!-- 
        '''    Microsoft ResX Schema 
        '''    
        '''    Version 2.0
        '''    
        '''    The primary goals of this format is to allow a simple XML format 
        '''    that is mostly human readable. The generation and parsing of the 
        '''    various data types are done through the TypeConverter classes 
        '''    associated with the data types.
        '''    
        '''    Example:
        '''    
        '''    ... ado.net/XML headers &amp; schema ...
        '''    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        '''    &lt;resheader n [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Recursos() As String
            Get
                Return ResourceManager.GetString("Recursos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;------------------------------------------------------------------------------
        '''&apos; &lt;auto-generated&gt;
        '''&apos;     This code was generated by a tool.
        '''&apos;     Runtime Version:4.0.30319.18052
        '''&apos;
        '''&apos;     Changes to this file may cause incorrect behavior and will be lost if
        '''&apos;     the code is regenerated.
        '''&apos; &lt;/auto-generated&gt;
        '''&apos;------------------------------------------------------------------------------
        '''
        '''Option Strict On
        '''Option Explicit On
        '''
        '''Imports System
        '''
        '''Namespace My.Resources
        '''    
        '''    &apos;This class was auto-g [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Recursos_Designer() As String
            Get
                Return ResourceManager.GetString("Recursos_Designer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;------------------------------------------------------------------------------
        '''&apos; &lt;auto-generated&gt;
        '''&apos;     This code was generated by a tool.
        '''&apos;     Runtime Version:4.0.30319.18052
        '''&apos;
        '''&apos;     Changes to this file may cause incorrect behavior and will be lost if
        '''&apos;     the code is regenerated.
        '''&apos; &lt;/auto-generated&gt;
        '''&apos;------------------------------------------------------------------------------
        '''
        '''Option Strict On
        '''Option Explicit On
        '''
        '''Imports System
        '''
        '''Namespace My.Resources
        '''    
        '''    &apos;This class was auto-g [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Recursos_Designer1() As String
            Get
                Return ResourceManager.GetString("Recursos_Designer1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;------------------------------------------------------------------------------
        '''&apos; &lt;auto-generated&gt;
        '''&apos;     This code was generated by a tool.
        '''&apos;     Runtime Version:4.0.30319.18052
        '''&apos;
        '''&apos;     Changes to this file may cause incorrect behavior and will be lost if
        '''&apos;     the code is regenerated.
        '''&apos; &lt;/auto-generated&gt;
        '''&apos;------------------------------------------------------------------------------
        '''
        '''Option Strict On
        '''Option Explicit On
        '''
        '''Imports System
        '''
        '''Namespace My.Resources
        '''    
        '''    &apos;This class was auto-g [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Recursos_Designer2() As String
            Get
                Return ResourceManager.GetString("Recursos_Designer2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;root&gt;
        '''  &lt;!-- 
        '''    Microsoft ResX Schema 
        '''    
        '''    Version 2.0
        '''    
        '''    The primary goals of this format is to allow a simple XML format 
        '''    that is mostly human readable. The generation and parsing of the 
        '''    various data types are done through the TypeConverter classes 
        '''    associated with the data types.
        '''    
        '''    Example:
        '''    
        '''    ... ado.net/XML headers &amp; schema ...
        '''    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        '''    &lt;resheader n [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Recursos1() As String
            Get
                Return ResourceManager.GetString("Recursos1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;root&gt;
        '''  &lt;!-- 
        '''    Microsoft ResX Schema 
        '''    
        '''    Version 2.0
        '''    
        '''    The primary goals of this format is to allow a simple XML format 
        '''    that is mostly human readable. The generation and parsing of the 
        '''    various data types are done through the TypeConverter classes 
        '''    associated with the data types.
        '''    
        '''    Example:
        '''    
        '''    ... ado.net/XML headers &amp; schema ...
        '''    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        '''    &lt;resheader n [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Recursos2() As String
            Get
                Return ResourceManager.GetString("Recursos2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SFSGE_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SFSGE_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SFSGE_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SFSGE_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property shaman() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("shaman", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
