'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18052
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Shaman.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property aguno() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("aguno", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Alicia___Tim_Burton_1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Alicia___Tim_Burton_1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property alicia_1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alicia_1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AÑOS_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AÑOS_50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AUTOMOVILISTA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AUTOMOVILISTA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bombera1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bombera1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bucanera_1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bucanera_1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bucanera_oro_1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bucanera_oro_1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cacique() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cacique", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CAMARERA_50_s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CAMARERA_50_s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CAN_CAN_MOD_I() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CAN_CAN_MOD_I", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CARNAVAL_VENECIANO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CARNAVAL_VENECIANO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cazafantasma_1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cazafantasma_1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHARLESTON_MOD_I() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHARLESTON_MOD_I", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHEFF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHEFF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property daphne__scooby_doo__1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("daphne__scooby_doo__1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DETECTIVE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DETECTIVE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ENFERMERA_MOD_I_LARGO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ENFERMERA_MOD_I_LARGO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ENFERMERA_MOD_II_CORTO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ENFERMERA_MOD_II_CORTO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property estatua_de_la_libertad1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("estatua_de_la_libertad1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Frutillitas__2__1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Frutillitas__2__1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frutillitas_1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frutillitas_1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gaisha_21_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gaisha_21_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GANGSTER_MOD_I() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GANGSTER_MOD_I", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GANGSTER_MOD_II() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GANGSTER_MOD_II", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property geisha_11_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("geisha_11_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GIRL_SCOUT_MOD_I() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GIRL_SCOUT_MOD_I", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GIRL_SCOUT_MOD_II() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GIRL_SCOUT_MOD_II", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Marge_Simpson_1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Marge_Simpson_1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MARINERA_MOD_I() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MARINERA_MOD_I", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MARINERA_MOD_II() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MARINERA_MOD_II", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MARINERA_MOD_III() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MARINERA_MOD_III", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MÉDICA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MÉDICA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property militar_1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("militar_1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property minnie_1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minnie_1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MUCAMA_MOD_I() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MUCAMA_MOD_I", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MUCAMA_MOD_II() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MUCAMA_MOD_II", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ODALISCA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ODALISCA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Olivia_1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Olivia_1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property piloto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("piloto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Pirata__2__1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pirata__2__1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pirata_1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pirata_1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property POLICIA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("POLICIA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PORRISTA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PORRISTA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PRESA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PRESA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PUNK_ROJO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PUNK_ROJO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PUNK_VERDE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PUNK_VERDE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property quuno() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("quuno", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rainbow_Brite_1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rainbow_Brite_1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;root&gt;
        '''  &lt;!-- 
        '''    Microsoft ResX Schema 
        '''    
        '''    Version 2.0
        '''    
        '''    The primary goals of this format is to allow a simple XML format 
        '''    that is mostly human readable. The generation and parsing of the 
        '''    various data types are done through the TypeConverter classes 
        '''    associated with the data types.
        '''    
        '''    Example:
        '''    
        '''    ... ado.net/XML headers &amp; schema ...
        '''    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        '''    &lt;resheader n [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Recursos() As String
            Get
                Return ResourceManager.GetString("Recursos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;------------------------------------------------------------------------------
        '''&apos; &lt;auto-generated&gt;
        '''&apos;     This code was generated by a tool.
        '''&apos;     Runtime Version:4.0.30319.18052
        '''&apos;
        '''&apos;     Changes to this file may cause incorrect behavior and will be lost if
        '''&apos;     the code is regenerated.
        '''&apos; &lt;/auto-generated&gt;
        '''&apos;------------------------------------------------------------------------------
        '''
        '''Option Strict On
        '''Option Explicit On
        '''
        '''Imports System
        '''
        '''Namespace My.Resources
        '''    
        '''    &apos;This class was auto-g [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Recursos_Designer() As String
            Get
                Return ResourceManager.GetString("Recursos_Designer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;------------------------------------------------------------------------------
        '''&apos; &lt;auto-generated&gt;
        '''&apos;     This code was generated by a tool.
        '''&apos;     Runtime Version:4.0.30319.18052
        '''&apos;
        '''&apos;     Changes to this file may cause incorrect behavior and will be lost if
        '''&apos;     the code is regenerated.
        '''&apos; &lt;/auto-generated&gt;
        '''&apos;------------------------------------------------------------------------------
        '''
        '''Option Strict On
        '''Option Explicit On
        '''
        '''Imports System
        '''
        '''Namespace My.Resources
        '''    
        '''    &apos;This class was auto-g [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Recursos_Designer1() As String
            Get
                Return ResourceManager.GetString("Recursos_Designer1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;------------------------------------------------------------------------------
        '''&apos; &lt;auto-generated&gt;
        '''&apos;     This code was generated by a tool.
        '''&apos;     Runtime Version:4.0.30319.18052
        '''&apos;
        '''&apos;     Changes to this file may cause incorrect behavior and will be lost if
        '''&apos;     the code is regenerated.
        '''&apos; &lt;/auto-generated&gt;
        '''&apos;------------------------------------------------------------------------------
        '''
        '''Option Strict On
        '''Option Explicit On
        '''
        '''Imports System
        '''
        '''Namespace My.Resources
        '''    
        '''    &apos;This class was auto-g [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Recursos_Designer2() As String
            Get
                Return ResourceManager.GetString("Recursos_Designer2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;root&gt;
        '''  &lt;!-- 
        '''    Microsoft ResX Schema 
        '''    
        '''    Version 2.0
        '''    
        '''    The primary goals of this format is to allow a simple XML format 
        '''    that is mostly human readable. The generation and parsing of the 
        '''    various data types are done through the TypeConverter classes 
        '''    associated with the data types.
        '''    
        '''    Example:
        '''    
        '''    ... ado.net/XML headers &amp; schema ...
        '''    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        '''    &lt;resheader n [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Recursos1() As String
            Get
                Return ResourceManager.GetString("Recursos1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;root&gt;
        '''  &lt;!-- 
        '''    Microsoft ResX Schema 
        '''    
        '''    Version 2.0
        '''    
        '''    The primary goals of this format is to allow a simple XML format 
        '''    that is mostly human readable. The generation and parsing of the 
        '''    various data types are done through the TypeConverter classes 
        '''    associated with the data types.
        '''    
        '''    Example:
        '''    
        '''    ... ado.net/XML headers &amp; schema ...
        '''    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        '''    &lt;resheader n [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Recursos2() As String
            Get
                Return ResourceManager.GetString("Recursos2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property REFEREE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("REFEREE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Reina_de_Corazones___Tim_Burton_1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reina_de_Corazones___Tim_Burton_1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property reina_de_corazones_1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reina_de_corazones_1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rockera1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rockera1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SFSGE_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SFSGE_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SFSGE_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SFSGE_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property shaman() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("shaman", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SOLDADO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SOLDADO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sombrerero_loco__alicia_en_el_pais_de_las_maravillas__1_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sombrerero_loco__alicia_en_el_pais_de_las_maravillas__1_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TAXISTA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TAXISTA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
