'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Articulos
    Public Property ID As Long
    Public Property Imagen As Byte()
    Public Property ImageUrl As String
    Public Property Codigo As String
    Public Property CategoriaId As Long
    Public Property Descripcion As String
    Public Property GeneroId As Byte
    Public Property Procedencia As String
    Public Property Precio As Nullable(Of Double)
    Public Property ValorAdquisicion As Nullable(Of Double)
    Public Property Observaciones As String
    Public Property regUsuarioId As Long
    Public Property regFechaHora As Date
    Public Property regTerminalId As Nullable(Of Long)

    Public Overridable Property ArticulosTalleStock As ICollection(Of ArticulosTalleStock) = New HashSet(Of ArticulosTalleStock)
    Public Overridable Property Categorias As Categorias
    Public Overridable Property Generos As Generos

End Class
