'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Categorias
    Public Property ID As Long
    Public Property Descripcion As String
    Public Property regUsuarioId As Long
    Public Property regFechaHora As Date
    Public Property regTerminalId As Nullable(Of Long)

    Public Overridable Property Articulos As ICollection(Of Articulos) = New HashSet(Of Articulos)

End Class
