'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Clientes
    Public Property ID As Long
    Public Property NroCliente As Nullable(Of Long)
    Public Property Apellido As String
    Public Property Nombre As String
    Public Property Sexo As String
    Public Property FecNacimiento As Nullable(Of Date)
    Public Property dmCalle As String
    Public Property dmAltura As Long
    Public Property dmPiso As String
    Public Property dmDepto As String
    Public Property LocalidadId As Nullable(Of Long)
    Public Property CodigoPostal As String
    Public Property TelefonoLinea As String
    Public Property TelefonoCelular As String
    Public Property Email As String
    Public Property Empresa As String
    Public Property TipoDocumentoId As Nullable(Of Long)
    Public Property NroDocumento As Nullable(Of Long)
    Public Property Observaciones As String
    Public Property regUsuarioId As Long
    Public Property regFechaHora As Nullable(Of Date)
    Public Property regTerminalId As Nullable(Of Long)

    Public Overridable Property Localidades As Localidades
    Public Overridable Property Movimientos As ICollection(Of Movimientos) = New HashSet(Of Movimientos)
    Public Overridable Property TipoDocumentos As TipoDocumentos

End Class
