'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EstadosMovimientos
    Public Property ID As Long
    Public Property MovimientoId As Long
    Public Property EstadoId As Long
    Public Property regFechaHora As Date
    Public Property regUsuarioId As Long

    Public Overridable Property Estados As Estados
    Public Overridable Property Movimientos As Movimientos

End Class
