'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Eventos
    Public Property ID As Byte
    Public Property Descripcion As String
    Public Property TipoEvento As Byte
    Public Property Contacto As String
    Public Property FechaEvento As Date
    Public Property Direccion As String
    Public Property Telefono As String
    Public Property regUsuarioId As Long
    Public Property regFechaHora As Date
    Public Property regTerminalId As Nullable(Of Long)

    Public Overridable Property EventosMovimientos As ICollection(Of EventosMovimientos) = New HashSet(Of EventosMovimientos)

End Class
