'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MovimientosArticulos
    Public Property ID As Long
    Public Property MovimientoId As Long
    Public Property Descripcion As String
    Public Property ArticuloTalleId As Long
    Public Property FecEntrega As Date
    Public Property OperacionId As Long
    Public Property FecDevolucion As Date
    Public Property Abona As Decimal
    Public Property Cantidad As Integer
    Public Property Importe As Decimal
    Public Property flgDevuelto As Byte
    Public Property regUsuarioId As Long
    Public Property regFechaHora As Date
    Public Property regTerminalId As Nullable(Of Long)

    Public Overridable Property ArticulosTalleStock As ArticulosTalleStock
    Public Overridable Property Movimientos As Movimientos
    Public Overridable Property Operaciones As Operaciones

End Class
