'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class PartyIdeaEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=PartyIdeaEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Articulos() As DbSet(Of Articulos)
    Public Property ArticulosTalleStock() As DbSet(Of ArticulosTalleStock)
    Public Property Categorias() As DbSet(Of Categorias)
    Public Property Clientes() As DbSet(Of Clientes)
    Public Property Estados() As DbSet(Of Estados)
    Public Property EstadosMovimientos() As DbSet(Of EstadosMovimientos)
    Public Property Eventos() As DbSet(Of Eventos)
    Public Property EventosMovimientos() As DbSet(Of EventosMovimientos)
    Public Property Generos() As DbSet(Of Generos)
    Public Property Localidades() As DbSet(Of Localidades)
    Public Property Movimientos() As DbSet(Of Movimientos)
    Public Property MovimientosArticulos() As DbSet(Of MovimientosArticulos)
    Public Property Operaciones() As DbSet(Of Operaciones)
    Public Property Talles() As DbSet(Of Talles)
    Public Property TipoDocumentos() As DbSet(Of TipoDocumentos)
    Public Property TipoEventos() As DbSet(Of TipoEventos)
    Public Property Usuarios() As DbSet(Of Usuarios)

End Class
