'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuarios
    Public Property ID As Long
    Public Property Identificacion As String
    Public Property Password As Byte()
    Public Property Apellido As String
    Public Property Nombre As String
    Public Property Activo As Byte
    Public Property regUsuarioId As Long
    Public Property regFechaHora As Date
    Public Property regTerminalId As Nullable(Of Long)
    Public Property flgAdmin As Byte

End Class
